spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # MySQL 설정
    hibernate:
      ddl-auto: update
    # 운영 환경에서는 "update" 대신 "validate" 또는 "none"을 사용하는 것이 좋습니다.

  datasource:
    url: jdbc:mysql://bopcon.czwmu86ms4yl.us-east-1.rds.amazonaws.com:3306/bopcon?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  issuer: seokjuun@gmail.com
  secret_key: bopconhongseokjun
